stages:
  - name: Publish PHP image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}
        pushRemote: true
        registry: harbor-demo.iiidevops.org
      env:
        PLUGIN_BUILD_ARGS: --progress=tty --network=host
        PLUGIN_DEBUG: "true"
        PLUGIN_INSECURE: "true"
        PLUGIN_MIRROR: https://harbor-demo.iiidevops.org
        PLUGIN_MTU: "1000"
    when:
      branch:
        include:
        - master
        - develop        

  # (選擇性) 原始碼資安掃描(必須有安裝設定 Checkmarx)
  - name: Scan source code
    steps:
    - applyAppConfig:
        catalogTemplate: cattle-global-data:iii-dev-charts3-source-scan
        version: 0.1.0
        name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-source-scan
        targetNamespace: ${CICD_GIT_REPO_NAME}
        answers:
          pipeline.sequence: ${CICD_EXECUTION_SEQUENCE}
          xip.ip: "10.20.0.77"
          harbor.host: "harbor-demo.iiidevops.org"
          # 基礎pipeline參數
          git.host: "gitlab-demo.iiidevops.org"
          git.url: ${CICD_GIT_URL}
          git.repoName: ${CICD_GIT_REPO_NAME}
          git.branch: ${CICD_GIT_BRANCH}
          git.commitID: "${CICD_GIT_COMMIT}"
          # web參數設定
          checkmarx.enabled: true
          checkmarx.runnerVersion: "latest"
    when:
      branch:
        include:
        - checkmarx

  # (選擇性)部屬使用者的資料庫
  - name: Deploy db
    steps:
      - applyAppConfig:
          catalogTemplate: cattle-global-data:iii-dev-charts3-db
          version: 0.1.0
          name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db
          #targetNamespace: p-v2nzs-pipeline
          targetNamespace: ${CICD_GIT_REPO_NAME}
          answers:
            # 設定 GitLab 的網址
            git.host: "gitlab-demo.iiidevops.org"
            # 這裡是為了告訴要處理的git來源為何
            git.repoName: ${CICD_GIT_REPO_NAME}
            git.branch: ${CICD_GIT_BRANCH}
            db.type: mariadb
            db.gui: true
            # 使用者資料庫管理密碼
            db.username: bear
            db.password: bearisbear
            # 使用者初始想要建立的資料庫名稱
            db.name: mytestdb
    when:
      branch:
        include:
          - master
  
  # 部屬使用者應用(app)
  - name: Deploy app-web
    steps:
    - applyAppConfig:
        catalogTemplate: cattle-global-data:iii-dev-charts3-web
        version: 0.2.1
        name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web
        #targetNamespace: p-v2nzs-pipeline
        targetNamespace: ${CICD_GIT_REPO_NAME}
        answers:
          pipeline.sequence: ${CICD_EXECUTION_SEQUENCE}
          xip.ip: "10.20.0.77"
          harbor.host: "harbor-demo.iiidevops.org"
          # 基礎pipeline參數
          git.host: "gitlab-demo.iiidevops.org"
          git.url: ${CICD_GIT_URL}
          git.branch: ${CICD_GIT_BRANCH}
          git.commitID: "${CICD_GIT_COMMIT}"
          git.repoName: ${CICD_GIT_REPO_NAME}
          # web參數設定
          web.type: php
          web.image: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}
          web.tag: ${CICD_GIT_BRANCH}
          newman.enabled: false
    when:
      branch:
        include:
        - master
        - develop        
